version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app
    
    networks:
      my_custom_network:
        ipv4_address: 172.19.0.3
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'newuserdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    networks:
      my_custom_network:
        ipv4_address: 172.19.0.2  

networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
