version: '3.2'

services:
  # Base de données MySQL
  db:
    image: mysql:5.7

    container_name: base_de_donnees

    volumes:
      - db_data:/var/lib/mysql
      - ./csv_data:/csv_data

    command: --innodb-use-native-aio=0

    environment:
      MYSQL_ROOT_PASSWORD: RotO5!
      MYSQL_DATABASE: ifspeak
      MYSQL_USER: speaktog
      MYSQL_PASSWORD: p@see9!

    networks:
      sui_network:
        ipv4_address: 192.168.2.30

  # Alpine
  serveur:
    image: nginx:alpine
    
    container_name: arl_pine
    
    depends_on:
      - db

    ports:
      - "8080:80"
      - "22:22"

    networks:
      sui_network:
        ipv4_address: 192.168.2.31

    configs:
      - source: install.sh
        target: ./install

    volumes:
      - dab_data:/var/www/htdocs
      - ./install:/install

networks:
  sui_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24

volumes:
  db_data:
  dab_data:
