version: '3'
services:
   s-app1:
      build: ./appli
      ports:
      - "5000"
   s-app2:
      build: ./appli
      ports:
      - "5000"
   s-nginx:
      build: ./nginx
      ports:
      - "8080:80"
      depends_on:
         - s-app1
         - s-app2