name: tests unitaires
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       matrix:
        python-version: ["3.8","3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Set up Pytest
        run: python -m pip install --upgrade pip
          pip install ruff pytest
      - name: Run tests
        run: pytest TP1/test.py
      - name: Version Pyton
        run: echo "Version de python ${{runner.name}}"
      - name: Branche
        run: echo "Nom branche ${{github.ref}}"
      - name: OS
        run: echo "Nom de  l'OS ${{runner.os}}"
